/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 *  Copyright (C) 2010 mscholl
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * ProxyAuthenticationPanel.java
 *
 * Created on Jul 5, 2010, 2:51:28 PM
 */
package de.cismet.cids.server.ws;

import org.openide.util.NbBundle;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class ProxyAuthenticationPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblComputerName;
    private javax.swing.JLabel lblDomain;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProxyURL;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtComputerName;
    private javax.swing.JTextField txtDomain;
    private javax.swing.JTextField txtProxyURL;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form ProxyAuthenticationPanel.
     */
    public ProxyAuthenticationPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    ProxyConfig getProxyConfig() {
        final ProxyConfig config = new ProxyConfig();
        config.setProxyURL(txtProxyURL.getText());
        config.setUsername(txtUsername.getText());
        config.setPassword(String.valueOf(pwdPassword.getPassword()));
        config.setComputerName(txtComputerName.getText());
        config.setDomain(txtDomain.getText());

        return config;
    }

    /**
     * DOCUMENT ME!
     *
     * @param  config  DOCUMENT ME!
     */
    void setProxyConfig(final ProxyConfig config) {
        txtProxyURL.setText(config.getProxyURL());
        txtUsername.setText(config.getUsername());
        txtComputerName.setText(config.getComputerName());
        txtDomain.setText(config.getDomain());
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public static ProxyConfig showProxyConfigDialog() {
        return showProxyConfigDialog(null);
    }

    /**
     * DOCUMENT ME!
     *
     * @param   proxyConfig  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public static ProxyConfig showProxyConfigDialog(final ProxyConfig proxyConfig) {
        final ProxyAuthenticationPanel panel = new ProxyAuthenticationPanel();
        if (proxyConfig != null) {
            panel.setProxyConfig(proxyConfig);
        }

        final JOptionPane optionPane = new JOptionPane(
                panel,
                JOptionPane.QUESTION_MESSAGE,
                JOptionPane.OK_CANCEL_OPTION);
        final JDialog dialog = optionPane.createDialog(null, "Provide Proxy Configuration");
        dialog.setModal(true);
        dialog.setVisible(true);
        dialog.requestFocus();

        final ProxyConfig config;
        if (JOptionPane.OK_OPTION == Integer.valueOf(optionPane.getValue().toString())) {
            config = panel.getProxyConfig();
        } else {
            config = null;
        }

        return config;
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        lblProxyURL = new javax.swing.JLabel();
        txtProxyURL = new javax.swing.JTextField();
        lblComputerName = new javax.swing.JLabel();
        txtComputerName = new javax.swing.JTextField();
        lblDomain = new javax.swing.JLabel();
        txtDomain = new javax.swing.JTextField();

        lblUsername.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.lblUsername.text")); // NOI18N

        txtUsername.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.txtUsername.text")); // NOI18N

        lblPassword.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.lblPassword.text")); // NOI18N

        pwdPassword.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.pwdPassword.text")); // NOI18N

        lblProxyURL.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.lblProxyURL.text")); // NOI18N

        txtProxyURL.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.txtProxyURL.text")); // NOI18N

        lblComputerName.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.lblComputerName.text")); // NOI18N

        txtComputerName.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.txtComputerName.text")); // NOI18N

        lblDomain.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.lblDomain.text")); // NOI18N

        txtDomain.setText(NbBundle.getMessage(ProxyAuthenticationPanel.class, "ProxyAuthenticationPanel.txtDomain.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(lblProxyURL)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtProxyURL, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblUsername)
                            .add(lblPassword)
                            .add(lblComputerName)
                            .add(lblDomain))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtComputerName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pwdPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, txtUsername, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .add(txtDomain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblProxyURL)
                    .add(txtProxyURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblUsername)
                    .add(txtUsername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblPassword)
                    .add(pwdPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblComputerName)
                    .add(txtComputerName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblDomain)
                    .add(txtDomain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
}
